// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpXiKz5SllY691SSxWJQ2xvKTY043YJwY',
    appId: '1:966312889345:web:529424234afc718cb6c400',
    messagingSenderId: '966312889345',
    projectId: 'fahad-870cb',
    authDomain: 'fahad-870cb.firebaseapp.com',
    storageBucket: 'fahad-870cb.firebasestorage.app',
    measurementId: 'G-ZZF7GH1LV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnXl7sMog6ioT0tgGJkpEjGwNzCK1x9xw',
    appId: '1:966312889345:android:8f9ff9ff917aa767b6c400',
    messagingSenderId: '966312889345',
    projectId: 'fahad-870cb',
    storageBucket: 'fahad-870cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFwegThDxxW7tEkFp2BEdGd6SGBSyWnYo',
    appId: '1:966312889345:ios:d4db7e8695a6a727b6c400',
    messagingSenderId: '966312889345',
    projectId: 'fahad-870cb',
    storageBucket: 'fahad-870cb.firebasestorage.app',
    iosBundleId: 'com.example.instgramApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFwegThDxxW7tEkFp2BEdGd6SGBSyWnYo',
    appId: '1:966312889345:ios:d4db7e8695a6a727b6c400',
    messagingSenderId: '966312889345',
    projectId: 'fahad-870cb',
    storageBucket: 'fahad-870cb.firebasestorage.app',
    iosBundleId: 'com.example.instgramApp',
  );
}
